name: Yarn Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

jobs:
  SFTP-deploy:
    name: ðŸª› Build
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: ðŸ”¨ Build Full Version - yarn
        run: |
          cd full-version
          corepack enable
          yarn set version 4.12.0
          yarn
          yarn build